{
 "title": "Cats and Dogs app Dashboard",
 "time": { "from": "2025-09-24T06:08:23.992Z", "to": "2025-09-24T23:17:23.810Z" },
 "panels": [
  {
   "title": "Temps d'inférence",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "catsdogs",
     "rawSql": "SELECT\r\n  $__timeGroup(timestamp, $__interval) AS time,\r\n  AVG(inference_time_ms) AS \"Temps d'inférence moyen (ms)\"\r\nFROM logs\r\nWHERE\r\n  $__timeFilter(timestamp) AND success = true\r\nGROUP BY 1\r\nORDER BY 1;\r\n"
    }
   ]
  },
  {
   "title": "Nombre de requête",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 11, "y": 0 },
   "targets": [
    {
     "dataset": "catsdogs",
     "rawSql": "SELECT\r\n  $__timeGroup(timestamp, $__interval) AS time,\r\n  COUNT(*) AS \"Nombre de requêtes\"\r\nFROM logs\r\nWHERE\r\n  $__timeFilter(timestamp)\r\nGROUP BY 1 \r\nORDER BY 1;\r\n"
    }
   ]
  },
  {
   "title": "Taux de précision (retours feedbacks) cumulé",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 7 },
   "targets": [
    {
     "dataset": "catsdogs",
     "rawSql": "WITH binned_feedbacks AS (\r\n  SELECT\r\n    $__timeGroup(timestamp, $__interval) AS time,\r\n    COUNT(*) FILTER (WHERE feedback = true) AS corrects,\r\n    COUNT(*) AS total\r\n  FROM feedbacks\r\n  WHERE $__timeFilter(timestamp)\r\n  GROUP BY 1\r\n)\r\nSELECT\r\n  time,\r\n  SUM(corrects) OVER (ORDER BY time) * 100.0 / SUM(total) OVER (ORDER BY time) AS \"Précision cumulative (%)\"\r\nFROM binned_feedbacks\r\nORDER BY time;\r\n\r\n"
    }
   ]
  },
  {
   "title": "Taux de précision selon la classe",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 11, "y": 7 },
   "targets": [
    {
     "dataset": "catsdogs",
     "rawSql": "WITH binned_feedbacks_by_class AS (\r\n  SELECT\r\n    $__timeGroup(timestamp, $__interval) AS time,\r\n    COUNT(*) FILTER (WHERE feedback = true AND predict_result = 'Cat') AS correct_cats,\r\n    COUNT(*) FILTER (WHERE predict_result = 'Cat') AS total_cats,\r\n    COUNT(*) FILTER (WHERE feedback = true AND predict_result = 'Dog') AS correct_dogs,\r\n    COUNT(*) FILTER (WHERE predict_result = 'Dog') AS total_dogs\r\n  FROM feedbacks\r\n  WHERE $__timeFilter(timestamp)\r\n  GROUP BY 1\r\n)\r\nSELECT\r\n  time,\r\n  SUM(correct_cats) OVER (ORDER BY time) * 100.0 / NULLIF(SUM(total_cats) OVER (ORDER BY time), 0) AS \"Précision cumulative 'Cat' (%)\",\r\n  SUM(correct_dogs) OVER (ORDER BY time) * 100.0 / NULLIF(SUM(total_dogs) OVER (ORDER BY time), 0) AS \"Précision cumulative 'Dog' (%)\"\r\nFROM binned_feedbacks_by_class\r\nORDER BY time;\r\n"
    }
   ]
  }
 ]
}